global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Productos Service
  - job_name: 'productos-service'
    static_configs:
      - targets: ['productos-service-prod:8081']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s
    scrape_timeout: 5s
    honor_labels: true

  # Inventario Service
  - job_name: 'inventario-service'
    static_configs:
      - targets: ['inventario-service-prod:8082']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s
    scrape_timeout: 5s
    honor_labels: true

  # PostgreSQL Databases
  - job_name: 'postgres-productos'
    static_configs:
      - targets: ['productos-db-prod:5432']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'postgres-inventario'
    static_configs:
      - targets: ['inventario-db-prod:5432']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Redis
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-prod:6379']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Nginx
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-prod:80']
    metrics_path: '/nginx_status'
    scrape_interval: 30s

  # Node Exporter (if running on host)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['host.docker.internal:9100']
    scrape_interval: 30s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

